// Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:lms_sdk/lms_sdk.dart';
import 'package:lms_sdk/src/common/application/schedule/schedule_notifier.dart'
    show ScheduleNotifier, ScheduleStore;

/// Skills app wiring (factory/docs/lesson-skills-schema.md). Two non-forcing
/// suggestion surfaces (assessment low-score branch, attendance hand-out) +
/// the library-only invariant (a skill lesson is never scheduled). The index
/// fixture below is the REAL generated `lessons/skills_index.json` from the
/// factory repo (commit 0d1a7d0 lineage), verbatim — these tests pin the
/// actual contract, not an invented shape.
const _realSkillsIndexJson = '''
{
  "_comment": [
    "GENERATED by lesson_pipeline.py skills-index — do not hand-edit.",
    "App-side contract for library-only skill lessons: a skill lesson",
    "is a full lesson (same seven content items) that never gets a",
    "live broadcast slot; it lives in the Library on demand. Cards",
    "reference skills via requires_skills: <skill_ref> — the app uses",
    "this for pre-session assessment skill-check tagging and the",
    "non-forcing 'review this skill first?' attendance suggestion."
  ],
  "generated": "2026-07-16 13:19:39",
  "skills": {
    "geography.map_scale_and_distance": {
      "card_id": "geography_g12_geographical_skills_and_techniques_map_scale_a_eb274e",
      "card_file": ".rokct/agent/jobs/pending/geography_g12_geographical_skills_and_techniques_map_scale_a_lesson.geography_eb274e.md",
      "subject": "Geography",
      "grade": 12,
      "topic": "Geographical Skills and Techniques",
      "subtopic": "Map scale and distance",
      "lesson_name": "",
      "lesson_path": "",
      "status": "pending_approval",
      "required_by": []
    },
    "geography.gradient_calculation": {
      "card_id": "geography_g12_geographical_skills_and_techniques_gradient_ca_dc21d0",
      "card_file": ".rokct/agent/jobs/done/geography_g12_geographical_skills_and_techniques_gradient_ca_lesson.geography_dc21d0.md",
      "subject": "Geography",
      "grade": 12,
      "topic": "Geographical Skills and Techniques",
      "subtopic": "Gradient calculation",
      "lesson_name": "Gradient calculation",
      "lesson_path": "lessons/geography/grade12/skills/geography_g12_geographical_skills_and_techniques_gradient_ca_dc21d0",
      "status": "evaluated",
      "required_by": [
        "geography_g12_geomorphology_river_profiles_and_rejuvenation_0d881d"
      ]
    }
  }
}
''';

SkillLessonIndex _realIndex() => SkillLessonIndex.parse(
    jsonDecode(_realSkillsIndexJson) as Map<String, dynamic>);

void main() {
  group('skills_index.json contract', () {
    test('parses the real generated index', () {
      final index = _realIndex();
      final gradient = index.lookup('geography.gradient_calculation');
      expect(gradient, isNotNull);
      expect(gradient!.servable, isTrue, reason: 'status evaluated');
      expect(gradient.displayName, 'Gradient calculation');
      expect(gradient.cardId,
          'geography_g12_geographical_skills_and_techniques_gradient_ca_dc21d0');
      expect(gradient.grade, 12);

      // pending_approval: known but NOT servable — must never be suggested.
      final mapScale = index.lookup('geography.map_scale_and_distance');
      expect(mapScale, isNotNull);
      expect(mapScale!.servable, isFalse);
      // lesson_name empty until Level 2 → displayName falls back.
      expect(mapScale.displayName, 'Map scale and distance');

      expect(index.servable.map((s) => s.skillRef),
          ['geography.gradient_calculation']);
    });

    test('requires_skills parses comma-separated (the job-card form) + list',
        () {
      expect(parseRequiresSkills('geography.gradient_calculation'),
          ['geography.gradient_calculation']);
      expect(
        parseRequiresSkills(
            'geography.gradient_calculation, geography.map_scale_and_distance'),
        [
          'geography.gradient_calculation',
          'geography.map_scale_and_distance'
        ],
      );
      expect(parseRequiresSkills(['a.b', ' c.d ']), ['a.b', 'c.d']);
      expect(parseRequiresSkills(null), isEmpty);
      expect(parseRequiresSkills(''), isEmpty);
    });

    test('skill-check question tagging rides the MCQ json (skill_ref)', () {
      final q = McqQuestion.fromJson({
        'id': 'sk1',
        'question': 'A contour interval is 20m over 400m. Gradient?',
        'options': ['1:10', '1:20', '1:40'],
        'correct_index': 1,
        'skill_ref': 'geography.gradient_calculation',
      });
      expect(q.skillRef, 'geography.gradient_calculation');
      // Ordinary questions stay untagged.
      expect(
          McqQuestion.fromJson({
            'id': 'q1',
            'question': 'x?',
            'options': ['a'],
            'correct_index': 0
          }).skillRef,
          isNull);
    });
  });

  group('library-only invariant', () {
    test('a skill lesson leaking into the feed is never scheduled', () async {
      final n = ScheduleNotifier(
        schedule: _FakeSchedule([
          _session(id: 'normal'),
          _session(id: 'leaked-skill', isSkillLesson: true),
        ]),
        store: _MemStore(),
        now: () => _base.subtract(const Duration(hours: 2)),
      );
      await n.init();
      expect(n.state.sessions.map((s) => s.sessionId), ['normal']);
      n.dispose();
    });

    test('library: active subscribers see the skills shelf (servable only)',
        () async {
      final n = LibraryNotifier(
        store: LibraryStore(kv: _MemStore()),
        accessSource: _FixedAccess(
            const AccessStatus(subscription: SubscriptionState.active)),
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      expect(n.state.skillLessons.map((s) => s.skillRef),
          ['geography.gradient_calculation']);
      n.dispose();
    });

    test(
        'library: lapsed keeps attended lessons but the skills shelf is '
        'library-NEW content — matrix denies it', () async {
      final n = LibraryNotifier(
        store: LibraryStore(kv: _MemStore()),
        accessSource: _FixedAccess(
            const AccessStatus(subscription: SubscriptionState.lapsed)),
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      expect(n.state.accessBlocked, isFalse);
      expect(n.state.skillLessons, isEmpty);
      n.dispose();
    });
  });

  group('attendance confirmation hand-out (surface 2)', () {
    test('confirmed session with requires_skills gains the skill line',
        () async {
      final n = _scheduleWith(
        session: _session(
            requiresSkills: const ['geography.gradient_calculation']),
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      await n.confirmAttendance(n.state.sessions.single);
      expect(n.state.assignment, isNotNull);
      expect(n.state.assignment!.skillSuggestions.map((s) => s.skillRef),
          ['geography.gradient_calculation']);
      // Non-forcing: the sheet dismisses exactly as before.
      n.dismissAssignment();
      expect(n.state.assignment, isNull);
      n.dispose();
    });

    test('non-servable and unknown skills are omitted, never fabricated',
        () async {
      final n = _scheduleWith(
        session: _session(requiresSkills: const [
          'geography.map_scale_and_distance', // pending_approval
          'maths.nonexistent_skill',
        ]),
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      await n.confirmAttendance(n.state.sessions.single);
      expect(n.state.assignment!.skillSuggestions, isEmpty);
      n.dispose();
    });

    test('no skills source wired → hand-out unchanged (no regression)',
        () async {
      final n = _scheduleWith(
        session: _session(
            requiresSkills: const ['geography.gradient_calculation']),
        skills: null,
      );
      await n.init();
      await n.confirmAttendance(n.state.sessions.single);
      expect(n.state.assignment, isNotNull);
      expect(n.state.assignment!.skillSuggestions, isEmpty);
      n.dispose();
    });
  });

  group('pre-session assessment low-score branch (surface 1)', () {
    const skillQ = McqQuestion(
      id: 'sk1',
      prompt: 'Gradient of 20m over 400m?',
      options: ['1:10', '1:20', '1:40'],
      correctIndex: 1,
      skillRef: 'geography.gradient_calculation',
    );
    const topicQ = McqQuestion(
        id: 'q1', prompt: 'x?', options: ['a', 'b'], correctIndex: 0);

    test('wrong answer on the skill-tagged question surfaces the refresher',
        () async {
      final n = _scheduleWith(
        session: _session(
            requiresSkills: const ['geography.gradient_calculation']),
        questions: const [skillQ, topicQ],
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      await n.confirmAttendance(n.state.sessions.single);
      n.startPreAssessment();
      n.answerCheck(0); // skill question: WRONG
      await Future<void>.delayed(const Duration(milliseconds: 1100));
      n.answerCheck(0); // topic question: correct
      await Future<void>.delayed(const Duration(milliseconds: 1100));

      expect(n.state.skipCheck, isNull);
      expect(n.state.skillRefreshers.map((s) => s.skillRef),
          ['geography.gradient_calculation']);
      // Non-forcing: dismissible, and nothing locked.
      expect(n.state.appLocked, isFalse);
      n.dismissSkillRefreshers();
      expect(n.state.skillRefreshers, isEmpty);
      n.dispose();
    });

    test('correct on the skill question → no refresher, even if the topic '
        'question was wrong (skill-specific, not overall score)', () async {
      final n = _scheduleWith(
        session: _session(
            requiresSkills: const ['geography.gradient_calculation']),
        questions: const [skillQ, topicQ],
        skills: _IndexSource(_realIndex()),
      );
      await n.init();
      await n.confirmAttendance(n.state.sessions.single);
      n.startPreAssessment();
      n.answerCheck(1); // skill question: correct
      await Future<void>.delayed(const Duration(milliseconds: 1100));
      n.answerCheck(1); // topic question: WRONG
      await Future<void>.delayed(const Duration(milliseconds: 1100));

      expect(n.state.skillRefreshers, isEmpty);
      expect(n.state.baselineScores.values.single, 50);
      n.dispose();
    });
  });
}

final _base = DateTime(2026, 7, 20, 15, 0);

ScheduledSession _session({
  String id = 's1',
  List<String> requiresSkills = const [],
  bool isSkillLesson = false,
}) =>
    ScheduledSession(
      sessionId: id,
      subject: 'Geography',
      topic: 'River profiles and rejuvenation',
      tutorName: 'Grandmaster',
      startTime: _base,
      requiresSkills: requiresSkills,
      isSkillLesson: isSkillLesson,
    );

ScheduleNotifier _scheduleWith({
  required ScheduledSession session,
  List<McqQuestion> questions = const [],
  SkillLessonSource? skills,
}) =>
    ScheduleNotifier(
      schedule: _FakeSchedule([session]),
      questions: _FakeQuestions(questions),
      skills: skills,
      store: _MemStore(),
      now: () => _base.subtract(const Duration(hours: 2)),
    );

class _FakeSchedule implements SessionScheduleSource {
  final List<ScheduledSession> sessions;
  _FakeSchedule(this.sessions);
  @override
  Future<List<ScheduledSession>> upcoming() async => sessions;
}

class _FakeQuestions implements SessionQuestionSource {
  final List<McqQuestion> questions;
  _FakeQuestions(this.questions);
  @override
  Future<List<McqQuestion>> questionsForSession(String sessionId) async =>
      questions;
}

class _IndexSource implements SkillLessonSource {
  final SkillLessonIndex index;
  _IndexSource(this.index);
  @override
  Future<SkillLessonInfo?> lookup(String skillRef) async =>
      index.lookup(skillRef);
  @override
  Future<List<SkillLessonInfo>> available() async => index.servable;
}

class _FixedAccess implements AccessStatusSource {
  final AccessStatus status;
  _FixedAccess(this.status);
  @override
  Future<AccessStatus> current() async => status;
}

class _MemStore implements ScheduleStore {
  final Map<String, Map<String, dynamic>> _data = {};
  @override
  Future<Map<String, dynamic>?> get(String collection, String key) async =>
      _data['$collection/$key'];
  @override
  Future<void> put(
          String collection, String key, Map<String, dynamic> value) async =>
      _data['$collection/$key'] = value;
}
