// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: 1,
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('ui_type', 6000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('schedule', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/schedule');
  }),
  TourStep('courses', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/courses');
  }),
  TourStep('tutors', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tutors');
  }),
  TourStep('library', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/library');
  }),
  TourStep('practice', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/practice');
  }),
  TourStep('league', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/league');
  }),
  TourStep('my_plan', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/my-plan');
  }),
  TourStep('profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/profile');
  }),
];
