// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/database/app_database.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lms_sdk/lms_sdk.dart';
import 'package:productivity_sdk/src/common/application/run/maintenance_plant.dart';
import 'package:productivity_sdk/src/common/application/run/maintenance_templates.dart';
import 'package:productivity_sdk/src/common/application/run/task_run.dart';
import 'package:productivity_sdk/src/common/infrastructure/repositories/todo_repository_impl.dart';
import 'package:productivity_sdk/src/common/presentation/run/task_run_view.dart';
import 'package:productivity_sdk/src/common/presentation/tasks/task_card.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  // Capture in dark mode: persist the same flag the in-app theme toggle
  // writes. AppNotifier reads it synchronously in its constructor (before
  // the first frame), so every still and reel starts dark.
  await LocalStorage.setAppThemeMode(true);
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any password, but the ADDRESS decides the
      // role it hands back (MockAuthRepository._demoRolesByEmail), and the
      // role decides whether this app's session_policy admits the session at
      // all. So each shell picks its own account with setup.demo_email in its
      // tour/app.tour.yaml; shells that leave it unset get the 'customer'
      // default. The timeout guards the post-session FCM sync, which can
      // stall on an emulator - navigation to the demo landing happens before
      // it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('grade_prompt', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/schedule');
  }),
  TourStep('schedule', 8000, true, (WidgetTester tester, StackRouter router) async {
    // The /schedule step above landed on GradeRolloverGate (demo ships
    // last year's grade). Its single FilledButton is the confirm CTA with
    // the suggested new grade preselected. Tolerant: if the gate is not
    // on screen (grade already confirmed this run), there is nothing to
    // tap and the schedule is already showing.
    //
    // The CTA sits at the bottom of the gate's Scaffold. ScheduleRouteView
    // used to paint the floating bottom nav over it, which won the hit
    // test: this tap landed on the nav's Discover slot, the grade was
    // never confirmed, and this step captured the tutor-discovery screen -
    // byte-identical to the later `tutors` still. The nav now folds away
    // while the gate is up (lms_sdk >= 1.16.0), so the tap reaches the
    // button. The check below states that out loud rather than silently
    // capturing the wrong screen if it ever regresses.
    final Finder cta = find.descendant(
      of: find.byType(GradeRolloverGate),
      matching: find.byType(FilledButton),
    );
    if (cta.evaluate().isNotEmpty) {
      await tester.tap(cta.first, warnIfMissed: false);
      // The runner never pumps (the app drives its own frames), so give
      // the confirm its round trip before looking again.
      await Future<void>.delayed(const Duration(seconds: 3));
      if (find.byType(GradeRolloverGate).evaluate().isNotEmpty) {
        throw StateError(
          'grade rollover gate still up after tapping its confirm CTA - '
          'something is covering the button; the schedule was not reached',
        );
      }
    }
  }),
  TourStep('courses', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/courses');
  }),
  TourStep('tutors', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tutors');
  }),
  TourStep('library', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/library');
  }),
  TourStep('practice', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/practice');
  }),
  TourStep('league', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/league');
  }),
  TourStep('my_plan', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/my-plan');
  }),
  TourStep('profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/profile');
  }),
  TourStep('sign_out_student', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('partner_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('partner@demo.rokct.ai');
      login.setPassword('demo-partners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('partner_dashboard', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-dashboard');
  }),
  TourStep('partner_add_student', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-add-student');
  }),
  TourStep('partner_sponsor_reports', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/sponsor-dashboard');
  }),
  TourStep('partner_profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-profile');
  }),
  TourStep('sign_out_partner', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('admin_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('admin@demo.rokct.ai');
      login.setPassword('demo-admins-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('admin_lesson_review', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/lesson-review');
  }),
  TourStep('admin_homework_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/homework-fulfilment');
  }),
  TourStep('admin_announcements', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/announcements-admin');
  }),
  TourStep('wallet_topup', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/wallet-topup');
  }),
  TourStep('wallet_history', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/wallet-history');
  }),
  TourStep('productivity_tasks', 7000, true, (WidgetTester tester, StackRouter router) async {
    final DateTime today = DateTime.now();
    DateTime at(int days, int hour) =>
        DateTime(today.year, today.month, today.day + days, hour);
    String ago(int hours) =>
        today.subtract(Duration(hours: hours)).toIso8601String();
    await TodoRepositoryImpl(AppDatabase()).saveTodos(
      <Map<String, dynamic>>[
        <String, dynamic>{
          'id': 'tour-task-depot-01',
          'notifId': 47101,
          'title': 'Deliver 40 × 20 L to the Mokopane depot',
          'isDone': false,
          'deadline': at(1, 9).toIso8601String(),
          'reminder': true,
          'priority': 'High',
          'category': 'Deliveries',
          'recurrence': 'Weekly',
          'createdAt': ago(2),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Load the bakkie', 'isDone': true},
            <String, dynamic>{
              'title': 'Collect the signed delivery note',
              'isDone': false,
            },
            <String, dynamic>{'title': 'Bring back the empties', 'isDone': false},
          ],
        },
        <String, dynamic>{
          'id': 'tour-task-brine-02',
          'notifId': 47102,
          'title': 'Order brine salt · 25 kg bags',
          'isDone': false,
          'deadline': at(2, 10).toIso8601String(),
          'reminder': false,
          'priority': 'Medium',
          'category': 'Plant',
          'recurrence': 'Monthly',
          'createdAt': ago(5),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Count the bags left', 'isDone': true},
            <String, dynamic>{'title': 'Send the order to the co-op', 'isDone': false},
          ],
        },
        <String, dynamic>{
          'id': 'tour-task-invoice-03',
          'notifId': 47103,
          'title': 'Chase the Polokwane Spar invoice',
          'isDone': false,
          'deadline': at(5, 12).toIso8601String(),
          'reminder': true,
          'priority': 'Low',
          'category': 'Admin',
          'recurrence': 'None',
          'createdAt': ago(9),
          'subtasks': <Map<String, dynamic>>[],
        },
        <String, dynamic>{
          'id': 'tour-task-borehole-04',
          'notifId': 47104,
          'title': 'Second borehole · quotes and water-use licence',
          'isDone': false,
          'reminder': false,
          'priority': 'Medium',
          'category': 'Plant',
          'recurrence': 'None',
          'isLongTerm': true,
          'createdAt': ago(30),
          'subtasks': <Map<String, dynamic>>[
            <String, dynamic>{'title': 'Three drilling quotes', 'isDone': true},
            <String, dynamic>{'title': 'Water-use licence application', 'isDone': false},
            <String, dynamic>{'title': 'Pump and tank sizing', 'isDone': false},
          ],
        },
      ],
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder card = find.byKey(
      const ValueKey<String>('task-card-tour-task-depot-01'),
    );
    if (card.evaluate().isNotEmpty) {
      await tester.tap(card.first, warnIfMissed: false);
    }
  }),
  TourStep('productivity_task_compose', 6000, true, (WidgetTester tester, StackRouter router) async {
    await MaintenancePlantStore.local.save(
      PlantRecord(
        megaCharVessels: 1,
        softenerVessels: 1,
        vesselsInstalledOn: DateTime(2026, 3, 14),
        preFilterInstalledOn: DateTime(2026, 8, 20),
        roFilterInstalledOn: DateTime(2026, 6, 1),
        postFilterInstalledOn: DateTime(2026, 6, 1),
        membranes: 2,
        membranesInstalledOn: DateTime(2026, 1, 10),
        recordedAt: DateTime.now(),
      ),
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder compose = find.byKey(const ValueKey<String>('tasks-compose'));
    if (compose.evaluate().isNotEmpty) {
      await tester.tap(compose.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    final Finder softener = find.byKey(
      const ValueKey<String>('template-softener_maintenance'),
    );
    if (softener.evaluate().isNotEmpty) {
      await tester.tap(softener.first, warnIfMissed: false);
    }
  }),
  TourStep('productivity_maintenance_readings', 6000, true, (WidgetTester tester, StackRouter router) async {
    final DateTime now = DateTime.now();
    final Map<String, dynamic> task = MaintenanceTemplates.build(
      MaintenanceTemplate.softenerMaintenance,
      now: now,
    );
    task['id'] = 'tour-softener-sft-02';
    task['notifId'] = 47021;
    task['title'] = 'Softener SFT-02 · Polokwane plant';
    task['category'] = 'Plant';
    task['createdAt'] = now.toIso8601String();
    TaskRun run = TaskRun.fromTask(task);
    DateTime at = now.subtract(const Duration(hours: 1, minutes: 5));
    for (int i = 0; i < 9; i++) {
      run = run.start(i, at);
      at = at.add(Duration(seconds: run.steps[i].durationSeconds));
      run = run.complete(i, at);
    }
    await TodoRepositoryImpl(AppDatabase()).saveTodos(
      <Map<String, dynamic>>[run.applyTo(task)],
    );
    router.replaceNamed('/tasks');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder runPill = find.descendant(
      of: find.byKey(const ValueKey<String>('task-card-tour-softener-sft-02')),
      matching: find.byKey(TaskCard.runKey),
    );
    if (runPill.evaluate().isNotEmpty) {
      await tester.tap(runPill.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 3));
    }
    final Finder resume = find.byKey(TaskRunView.resumeKey);
    if (resume.evaluate().isNotEmpty) {
      await tester.tap(resume.first, warnIfMissed: false);
      await Future<void>.delayed(const Duration(seconds: 1));
    }
    const List<String> readings = <String>['175', '212', '8.4', '1.9'];
    for (int i = 0; i < readings.length; i++) {
      final Finder field = find.byKey(TaskRunView.readingKey(i));
      if (field.evaluate().isNotEmpty) {
        await tester.enterText(field.first, readings[i]);
        await tester.pump();
      }
    }
  }),
  TourStep('productivity_maintenance_photo', 6000, true, (WidgetTester tester, StackRouter router) async {
    final Finder permeate = find.byKey(TaskRunView.readingKey(1));
    if (permeate.evaluate().isNotEmpty) {
      await tester.enterText(permeate.first, '40');
      await tester.pump();
    }
    final Finder forward = find.byKey(TaskRunView.continueKey);
    if (forward.evaluate().isNotEmpty) {
      await tester.tap(forward.first, warnIfMissed: false);
    }
  }),
];
