// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lms_sdk/lms_sdk.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('grade_prompt', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/schedule');
  }),
  TourStep('schedule', 8000, true, (WidgetTester tester, StackRouter router) async {
    // The /schedule step above landed on GradeRolloverGate (demo ships
    // last year's grade). Its single FilledButton is the confirm CTA with
    // the suggested new grade preselected. Tolerant: if the gate is not
    // on screen (grade already confirmed this run), there is nothing to
    // tap and the schedule is already showing.
    final Finder cta = find.descendant(
      of: find.byType(GradeRolloverGate),
      matching: find.byType(FilledButton),
    );
    if (cta.evaluate().isNotEmpty) {
      await tester.tap(cta.first, warnIfMissed: false);
    }
  }),
  TourStep('courses', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/courses');
  }),
  TourStep('tutors', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tutors');
  }),
  TourStep('library', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/library');
  }),
  TourStep('practice', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/practice');
  }),
  TourStep('league', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/league');
  }),
  TourStep('my_plan', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/my-plan');
  }),
  TourStep('profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/profile');
  }),
  TourStep('sign_out_student', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('partner_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('partner@demo.rokct.ai');
      login.setPassword('demo-partners-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('partner_dashboard', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-dashboard');
  }),
  TourStep('partner_add_student', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-add-student');
  }),
  TourStep('partner_sponsor_reports', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/sponsor-dashboard');
  }),
  TourStep('partner_profile', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/partner-profile');
  }),
  TourStep('sign_out_partner', 4000, false, (WidgetTester tester, StackRouter router) async {
    LocalStorage.logout();
    router.replaceNamed('/login');
  }),
  TourStep('admin_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('admin@demo.rokct.ai');
      login.setPassword('demo-admins-2026');
      // MockAuthRepository accepts any credentials. The timeout guards the
      // post-session FCM sync, which can stall on an emulator - navigation
      // to the demo landing happens before it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('admin_lesson_review', 10000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/lesson-review');
  }),
  TourStep('admin_homework_queue', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/homework-fulfilment');
  }),
  TourStep('admin_announcements', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/announcements-admin');
  }),
  TourStep('wallet_topup', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/wallet-topup');
  }),
  TourStep('productivity_tasks', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tasks');
  }),
];
