
import 'package:flutter/widgets.dart';

/// Navigation indirection for SDK-resident code.
///
/// Route classes are generated by auto_route inside the HOST app, so SDK
/// packages cannot reference them. Instead SDK code calls the typed methods
/// on [AppRoutes.I]; the host app assigns an implementation (backed by its
/// generated router) during bootstrap, before any SDK page can navigate.
abstract class AppRoutes {
  static AppRoutes I = _UnsetAppRoutes();

  Future<Object?> pushAddressListRoute(BuildContext context);
  Future<Object?> pushChatRoute(BuildContext context, {dynamic name, dynamic roleId});
  Future<Object?> replaceClosedRoute(BuildContext context);
  Future<Object?> pushCreateShopRoute(BuildContext context);
  Future<Object?> pushHelpRoute(BuildContext context);
  Future<Object?> pushInfoRoute(BuildContext context, {dynamic index});
  Future<Object?> replaceInfoRoute(BuildContext context, {dynamic index});
  Future<Object?> pushLikeRoute(BuildContext context);
  Future<Object?> pushLoginRoute(BuildContext context);
  Future<Object?> replaceLoginRoute(BuildContext context);
  Future<Object?> pushMapSearchRoute(BuildContext context);
  Future<Object?> replaceNoConnectionRoute(BuildContext context);
  Future<Object?> pushNotificationListRoute(BuildContext context);
  Future<Object?> pushOrderProgressRoute(BuildContext context, {dynamic orderId});
  Future<Object?> pushOrderRoute(BuildContext context);
  Future<Object?> pushOrdersListRoute(BuildContext context);
  Future<Object?> replaceOrdersListRoute(BuildContext context);
  Future<Object?> pushParcelListRoute(BuildContext context);
  Future<Object?> replaceParcelListRoute(BuildContext context);
  Future<Object?> pushParcelProgressRoute(BuildContext context, {dynamic parcelId});
  Future<Object?> pushParcelRoute(BuildContext context);
  Future<Object?> pushProfileRoute(BuildContext context);
  Future<Object?> pushRecommendedOneRoute(BuildContext context, {dynamic isNewsOfPage, dynamic isShop});
  Future<Object?> pushRecommendedRoute(BuildContext context, {dynamic isShop, dynamic isNewsOfPage});
  Future<Object?> pushRecommendedThreeRoute(BuildContext context, {dynamic isNewsOfPage, dynamic isShop});
  Future<Object?> pushRecommendedTwoRoute(BuildContext context, {dynamic isNewsOfPage, dynamic isPopular, dynamic isShop});
  Future<Object?> pushResultFilterRoute(BuildContext context, {dynamic categoryId});
  Future<Object?> pushSearchRoute(BuildContext context);
  Future<Object?> pushServiceTwoCategoryRoute(BuildContext context, {dynamic index});
  Future<Object?> pushSettingRoute(BuildContext context);
  Future<Object?> pushShareReferralFaqRoute(BuildContext context, {dynamic terms});
  Future<Object?> pushShareReferralRoute(BuildContext context);
  Future<Object?> pushShopDetailRoute(BuildContext context, {dynamic shop, dynamic workTime});
  Future<Object?> pushShopRoute(BuildContext context, {dynamic productId, dynamic shop, dynamic shopId});
  Future<Object?> replaceShopRoute(BuildContext context, {dynamic productId, dynamic shop, dynamic shopId});
  Future<Object?> replaceMainRoute(BuildContext context);
  Future<Object?> pushShopsBannerRoute(BuildContext context, {dynamic bannerId, dynamic isAds, dynamic title});
  Future<Object?> replaceSplashRoute(BuildContext context);
  Future<Object?> pushStoryListRoute(BuildContext context, {dynamic controller, dynamic index});
  Future<Object?> replaceUiTypeRoute(BuildContext context);
  Future<Object?> pushViewMapRoute(BuildContext context, {dynamic address, dynamic indexAddress, dynamic isParcel, dynamic isPop, dynamic isShopLocation, dynamic shopId});
  Future<Object?> pushWalletHistoryRoute(BuildContext context);
}

class _UnsetAppRoutes implements AppRoutes {
  @override
  dynamic noSuchMethod(Invocation invocation) =>
      throw StateError(
          'AppRoutes.I has not been set by the host app. Assign an '
          'implementation in main() before running the app.');
}
