name: Code Quality
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-linter.yml@main
    with:
      run-build-runner: true
    secrets: inherit
