name: Auto Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    uses: RokctAI/shared-workflows/.github/workflows/universal-merge.yml@main
    permissions: write-all
    with:
      allowed_users: 'RendaniSinyage, Rendani Sinyage, rokctbot, rokctbot[bot]'
    secrets: inherit
