name: Security Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-security.yml@main
    secrets: inherit
